In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("beverage_r.csv", sep=";")

    numb.obs  COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
0          1     1       0        0      0      1       1    0        1
1          2     1       0        0      0      1       0    0        0
2          3     1       0        0      0      1       0    0        0
3          4     0       1        0      1      0       0    1        0
4          5     1       0        0      0      1       0    0        0
5          6     1       0        0      0      1       1    0        0
6          7     0       1        1      1      0       0    1        0
7          8     1       1        0      0      1       1    0        1
8          9     1       1        0      0      0       1    1        1
9         10     1       0        0      0      1       0    0        1
10        11     1       0        0      0      1       1    0        0
11        12     0       1        0      0      0       0    1        0
12        13     0       0        1      1      0       1    0        1
13        14     1       0        0      0      0       1    0        0
14        15     0       1        1      0      0       0    1        0
15        16     0       0        0      0      1       1    0        0
16        17     0       1        0      0      0       1    0        0
17        18     1       1        0      0      1       0    0        0
18        19     1       0        0      0      0       0    0        1
19        20     1       1        1      0      1       0    0        0
20        21     1       0        0      0      1       0    0        0
21        22     1       0        0      0      1       0    0        0
22        23     0       1        0      1      0       0    1        0
23        24     1       1        0      0      1       0    0        0
24        25     0       1        1      1      0       0    0        0
25        26     0       1        0      1      0       0    1        0
26        27     0       1        0      0      0       0    1        0
27        28     1       0        0      0      0       1    0        1
28        29     1       0        0      0      0       1    0        0
29        30     0       1        1      0      0       0    1        0
30        31     1       0        0      0      1       0    0        1
31        32     0       1        1      0      0       0    1        0
32        33     1       0        0      0      1       0    0        1
33        34     0       1        1      1      0       0    1        0