In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("beverage_r.csv", sep=";", index_col="numb.obs")

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
1            1       0        0      0      1       1    0        1
2            1       0        0      0      1       0    0        0
3            1       0        0      0      1       0    0        0
4            0       1        0      1      0       0    1        0
5            1       0        0      0      1       0    0        0
6            1       0        0      0      1       1    0        0
7            0       1        1      1      0       0    1        0
8            1       1        0      0      1       1    0        1
9            1       1        0      0      0       1    1        1
10           1       0        0      0      1       0    0        1
11           1       0        0      0      1       1    0        0
12           0       1        0      0      0       0    1        0
13           0       0        1      1      0       1    0        1
14           1       0        0      0      0       1    0        0
15           0       1        1      0      0       0    1        0
16           0       0        0      0      1       1    0        0
17           0       1        0      0      0       1    0        0
18           1       1        0      0      1       0    0        0
19           1       0        0      0      0       0    0        1
20           1       1        1      0      1       0    0        0
21           1       0        0      0      1       0    0        0
22           1       0        0      0      1       0    0        0
23           0       1        0      1      0       0    1        0
24           1       1        0      0      1       0    0        0
25           0       1        1      1      0       0    0        0
26           0       1        0      1      0       0    1        0
27           0       1        0      0      0       0    1        0
28           1       0        0      0      0       1    0        1
29           1       0        0      0      0       1    0        0
30           0       1        1      0      0       0    1        0
31           1       0        0      0      1       0    0        1
32           0       1        1      0      0       0    1        0
33           1       0        0      0      1       0    0        1
34           0       1        1      1      0       0    1        0